version: 2
sources:
- name: store-transaction-analysis
  database: store-transaction-analysis
  schema: store-transaction-models
  tables:
  - name: device_source
  - name: store_source
  - name: transaction_source
